### ISSUE TITLE
Surface Laptop Studio

### ISSUE THREAD

**Issue by ukasuviok** [linux-surface/acpidumps#20]
[acpidump.txt](https://github.com/linux-surface/acpidumps/files/7315654/acpidump.txt)

**Comment by qzed** [comment]
Thanks! Can you update the [feature matrix](https://github.com/linux-surface/linux-surface/wiki/Supported-Devices-and-Features#surface-laptops) and also run `./scripts/diagnostics.sh full` from the [linux-surface repo](https://github.com/linux-surface/linux-surface/blob/master/scripts/diagnostics.sh) and upload the generated archive?

**Comment by ukasuviok** [comment]
[diagnostics.tar.gz](https://github.com/linux-surface/acpidumps/files/7316139/diagnostics.tar.gz)
I can't boot of off the surface kernel in Fedora 34 for some reason.  I'm going to try using Ubuntu 21.04 and see how that goes. 
 Diagnostics are attached.

**Comment by ukasuviok** [comment]
I was able to boot of off the surface kernel using Ubuntu 21.04.  I also update the feature matrix.  For the items that are still question marks I wasn't sure how to test or was unclear what the item is.

**Comment by qzed** [comment]
Thanks again!  One more question: Does wakeup via the lid work? That might also need a patch.

> For the items that are still question marks I wasn't sure how to test or was unclear what the item is.

- In your case "buttons" refer to the power button. On other devices there are also separate volume buttons (away from keyboard) but I don't think that's the case on the SLS (please correct me if I'm wrong).
- "S0ix" refers to a special power saving state when suspended. There's more info on that [here](https://01.org/blogs/qwang59/2018/how-achieve-s0ix-states-linux) or on [this](https://github.com/linux-surface/linux-surface/wiki/Known-Issues-and-FAQ#general-info-about-s0ix) wiki page if you want to have a closer look at that. The short version is (if I remember correctly) if `sudo cat /sys/devices/system/cpu/cpuidle/low_power_idle_cpu_residency_us` returns a number that increases during suspend then S0ix should work.
-  "Sensors" refers to ambient light sensor and sensors for device rotation.
- "Performance modes" refer to the ACPI platform profile, which should allow you to configure the cooling/performance mode (e.g. via the `surface profile` command from the `surface-control` package). This should not work yet since the other Surface Aggregator Module stuff (keyboard, battery) doesn't work yet either and needs to be enabled first.


I've opened https://github.com/linux-surface/linux-surface/issues/596 for keyboard/touchpad and battery support. That should (hopefully) be fairly straight-forward to fix.

Unfortunately, for touchscreen/pen the device seems to rely on the Intel Touch Host Contoller which we neither have a driver nor specs for to write one. So unfortunately there's no estimate on how long it will take to get that working, if ever

**Comment by ukasuviok** [comment]
Wakeup via the lid does not work. I update the matrix based on the info you
provided.  Thanks for the help!

**Comment by qzed** [comment]
Perfect, thanks! Going to close this, let's address the problems in the respective issues:
- https://github.com/linux-surface/linux-surface/issues/596
- https://github.com/linux-surface/linux-surface/issues/597
